### PR TITLE
Fix attendance bugs when sorting, filtering, and clicking rows

### PR DESCRIPTION
**Pull request by brittanylau**
### Implementation description

- fixing some 🐛🐛🐛 

### Steps to test

verify that:
1. when users check/uncheck boxes in edit mode, the sidebar does not open
2. users cannot sort by date columns
3. users cannot filter, search, or hide columns

### What should reviewers focus on?

- testing

### Checklist

- [x] My PR name is descriptive and in imperative tense
- [x] I have run the linter
- [x] I have requested a review from the PL, and/or other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Review by Tayef-Shah — COMMENTED** [review]
The fixes look good, and it works locally. However, the first and last name sorting is kinda wonky on my end, because the first name column doesn't change when the last name is sorted. I sent some screenshots of the top few names in attendance with no sort, sort asc, and sort desc.

Screen Shot 2021-09-28 at 8 19 12 PM
Screen Shot 2021-09-28 at 8 19 20 PM
Screen Shot 2021-09-28 at 8 19 26 PM

**Comment by brittanylau** [comment]
@Tayef-Shah ugh you're right, i just disabled sort for the whole table LOL

**Comment by brittanylau** [comment]
@Tayef-Shah going to merge to have ready for the start of the week, but can put up another PR if we want more changes

**Comment by Tayef-Shah** [comment]
Looks fine to me

**Pull request merged**
