### PR TITLE
[4/5] Set up registration form inputs & submission

### PR DESCRIPTION
**Pull request by brittanylau**
### Notion ticket link

[Set up reg form inputs & submit to POST /families](https://www.notion.so/uwblueprintexecs/9cb454262ed84c6299c0682c23f92ec5?v=1076bd30711a4a01838becee05f8b5a3&p=3772e0140c85481e93c6394fff197608)

lots of next steps for this, will be adding follow-up tasks on notion 🏃‍♀️ 

### Implementation description

- filled in the `RegistrationForm` component with the default & dynamic fields for families, parents, children, and guests
  - it uses a `FormFieldGroup` component for each of the different "parts" of data ("default" and "dynamic" fields for each type of student) that go into the POST /families endpoint for ease of structuring the payload
  - so far it defaults to one child and one guest – adding/removing children & guests will come in a follow-up task
- created a `FormFieldGroup` component that renders inputs based on the provided fields
- added the POST family endpoint to the api utils

### Steps to test

there will be an automated test in the next PR! to test manually:

1. `yarn start`
2. open the registration form
3. fill in some data & submit
  - if the info is invalid, an alert will show (form validations to come later)
  - otherwise it takes you back to the "Add a client" view, and your new family should show in the reg table!

Screen Shot 2021-04-29 at 9 31 12 PM

### What should reviewers focus on?

- code cleanliness
- is there a better way to write anything? let me know 😄 

### Checklist

- [x] My PR name is descriptive and in imperative tense
- [x] I have run the linter
- [x] I have requested a review from the PL, and/or other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Review by jolenezheng — COMMENTED** [review]
If I don't input mandatory fields (names) and/or children/family member data I don't think I get an alert (I'm assuming it's like a toast alert, but lmk if I'm just missing something!)

**Comment by brittanylau** [comment]
> If I don't input mandatory fields (names) and/or children/family member data I don't think I get an alert (I'm assuming it's like a toast alert, but lmk if I'm just missing something!)

@jolenezheng are you running it on the deploy preview or on local? the alert shows if the server returns an error, but since the deploy preview isn't on the server's allowlist yet (PR coming soon), it won't show up for now. my bad for not clarifying!

let me know if it works on your local!

**Comment by jolenezheng** [comment]
> > If I don't input mandatory fields (names) and/or children/family member data I don't think I get an alert (I'm assuming it's like a toast alert, but lmk if I'm just missing something!)
> 
> @jolenezheng are you running it on the deploy preview or on local? the alert shows if the server returns an error, but since the deploy preview isn't on the server's allowlist yet (PR [here](https://github.com/uwblueprint/project-read-backend/pull/52)), it won't show up for now. my bad for not clarifying!
> 
> let me know if it works on your local!

I was running on my local 😯

**Review by Tayef-Shah — COMMENTED** [review]
I was registered but my phone number didn't show up hmm. Edit: Wait is that supposed to show preferred phone? If so, that makes sense.

Screen Shot 2021-05-11 at 8 25 13 PM

**Comment by Tayef-Shah** [comment]
> If I don't input mandatory fields (names) and/or children/family member data I don't think I get an alert (I'm assuming it's like a toast alert, but lmk if I'm just missing something!)

@brittanylau it's the same situation from my end. I'm seeing `Bad Request: /families/` in the backend each time I submit a registration without all the mandatory fields. However, the front end is silent and brings me back to the `/sessions` page.

**Comment by brittanylau** [comment]
working on a fix :) thanks for reviewing y'all!

**Comment by brittanylau** [comment]
> I was registered but my phone number didn't show up hmm. Edit: Wait is that supposed to show preferred phone? If so, it makes sense for it to not be there.

@Tayef-Shah yup the family serializer returns the number of the preferred phone - see the [serializer](https://github.com/uwblueprint/project-read-backend/blob/42dffd8a2dd55a78fa608a52d292093a53012487/registration/serializers.py#L43) and [model property](https://github.com/uwblueprint/project-read-backend/blob/42dffd8a2dd55a78fa608a52d292093a53012487/registration/models.py#L51-L58) for deets

**Comment by Tayef-Shah** [comment]
If you open the registration form without loading the dummy data first, several of the input fields are missing from the form. If you register a family without the dummy data being there, you can still see them in the registration table. However, first name and last name are not showing up, but are showing in the dialog.

Screen Shot 2021-05-13 at 9 13 37 AM

Screen Shot 2021-05-13 at 9 13 51 AM

**Review by Tayef-Shah — APPROVED** [review]
LGTM! Sorry for the delay :)))))

**Comment by brittanylau** [comment]
bug described above is fixed in the ts migration in #22

thanks for reviewing!!! 😄

**Pull request merged**
